sudo: required

services:
  - docker

before_install:
  - docker build -t irahulsah/react-docker-website -f Dockerfile.dev .


script:
  - docker run -e CI=true irahulsah/react-docker-website npm run test